format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'


# "$schema" = 'https://starship.rs/config-schema.json'
#
# format = """
# [](color_surface0)\
# $os\
# $username\
# [](bg:color_red fg:color_surface0)\
# $directory\
# [](fg:color_red bg:color_green)\
# $git_branch\
# $git_status\
# [](fg:color_green bg:color_yellow)\
# $c\
# $rust\
# $golang\
# $nodejs\
# $php\
# $java\
# $kotlin\
# $haskell\
# $python\
# [](fg:color_yellow bg:color_blue)\
# $docker_context\
# $conda\
# [](fg:color_blue bg:color_pink)\
# $time\
# [ ](fg:color_pink)\
# $line_break$character"""
#
# palette = 'gruvbox_dark'
#
# [palettes.gruvbox_dark]
# color_fg0 = '#fbf1c7'
# color_bg1 = '#3c3836'
# color_bg3 = '#665c54'
# color_aqua = '#7dc4e4'
# color_orange = '#ef9f76'
# color_purple = '#c6a0f6'
#
# color_rosewater = "#f4dbd6"
# color_flamingo = "#f0c6c6"
# color_pink = "#f5bde6"
# color_mauve = "#c6a0f6"
# color_red = "#ed8796"
# color_maroon = "#ee99a0"
# color_peach = "#f5a97f"
# color_yellow = "#eed49f"
# color_green = "#a6da95"
# color_teal = "#8bd5ca"
# color_sky = "#91d7e3"
# color_sapphire = "#7dc4e4"
# color_blue = "#8aadf4"
# color_lavender = "#b7bdf8"
# color_text = "#cad3f5"
# color_subtext1 = "#b8c0e0"
# color_subtext0 = "#a5adcb"
# color_overlay2 = "#939ab7"
# color_overlay1 = "#8087a2"
# color_overlay0 = "#6e738d"
# color_surface2 = "#5b6078"
# color_surface1 = "#494d64"
# color_surface0 = "#363a4f"
# color_base = "#24273a"
# color_mantle = "#1e2030"
# color_crust = "#181926"
#
# [os]
# disabled = false
# style = "bg:color_surface0 fg:color_fg0"
#
# [os.symbols]
# Windows = "󰍲"
# Ubuntu = "󰕈"
# SUSE = ""
# Raspbian = "󰐿"
# Mint = "󰣭"
# Macos = "󰀵"
# Manjaro = ""
# Linux = "󰌽"
# Gentoo = "󰣨"
# Fedora = "󰣛"
# Alpine = ""
# Amazon = ""
# Android = ""
# Arch = "󰣇"
# Artix = "󰣇"
# CentOS = ""
# Debian = "󰣚"
# Redhat = "󱄛"
# RedHatEnterprise = "󱄛"
#
# [username]
# show_always = true
# style_user = "bg:color_surface0 fg:color_fg0"
# style_root = "bg:color_surface0 fg:color_fg0"
# format = '[ $user ]($style)'
#
# [directory]
# style = "fg:color_crust bg:color_red"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"
#
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = "󰝚 "
# "Pictures" = " "
# "Desktop/EWAN VAULT" = "󰲋 "
#
# [git_branch]
# symbol = ""
# style = "bg:color_green"
# format = '[[ $symbol $branch ](fg:color_crust bg:color_green)]($style)'
#
# [git_status]
# style = "bg:color_green"
# format = '[[($all_status$ahead_behind )](fg:color_crust bg:color_green)]($style)'
#
# [nodejs]
# symbol = ""
# style = "bg:color_yellow"
# format = '[[ $symbol( $version) ](fg:color_crust bg:color_yellow)]($style)'
#
# [c]
# symbol = " "
# style = "bg:color_yellow"
# format = '[[ $symbol( $version) ](fg:color_crust bg:color_yellow)]($style)'
#
# [rust]
# symbol = ""
# style = "bg:color_yellow"
# format = '[[ $symbol( $version) ](fg:color_crust bg:color_yellow)]($style)'
#
# [golang]
# symbol = ""
# style = "bg:color_yellow"
# format = '[[ $symbol( $version) ](fg:color_crust bg:color_yellow)]($style)'
#
# [php]
# symbol = ""
# style = "bg:color_yellow"
# format = '[[ $symbol( $version) ](fg:color_crust bg:color_yellow)]($style)'
#
# [java]
# symbol = " "
# style = "bg:color_yellow"
# format = '[[ $symbol( $version) ](fg:color_crust bg:color_yellow)]($style)'
#
# [kotlin]
# symbol = ""
# style = "bg:color_yellow"
# format = '[[ $symbol( $version) ](fg:color_crust bg:color_yellow)]($style)'
#
# [haskell]
# symbol = ""
# style = "bg:color_yellow"
# format = '[[ $symbol( $version) ](fg:color_crust bg:color_yellow)]($style)'
#
# [python]
# symbol = ""
# style = "bg:color_yellow"
# format = '[[ $symbol( $version) ](fg:color_crust bg:color_yellow)]($style)'
#
# [docker_context]
# symbol = ""
# style = "bg:color_blue"
# format = '[[ $symbol( $context) ](fg:color_crust bg:color_blue)]($style)'
#
# [conda]
# style = "bg:color_blue"
# format = '[[ $symbol( $environment) ](fg:color_crust bg:color_blue)]($style)'
#
# [time]
# disabled = false
# time_format = "%R"
# style = "bg:color_ping"
# format = '[[  $time ](fg:color_crust bg:color_pink)]($style)'
#
# [line_break]
# disabled = false
#
# [character]
# disabled = false
# success_symbol = '[](bold fg:color_green)'
# error_symbol = '[](bold fg:color_red)'
# vimcmd_symbol = '[](bold fg:color_green)'
# vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
# vimcmd_replace_symbol = '[](bold fg:color_purple)'
# vimcmd_visual_symbol = '[](bold fg:color_yellow)'
